package main

import (
	"log"
	"os"

	"nexfi-backend/api/routes"
	"nexfi-backend/config"
	"nexfi-backend/database"
	"nexfi-backend/database/seeds"
	_ "nexfi-backend/docs" // Import docs generated by swag
	"nexfi-backend/pkg/livekit"
	"nexfi-backend/pkg/mqtt"
	"nexfi-backend/pkg/rabbitmq"
	"nexfi-backend/pkg/redis"
	"nexfi-backend/pkg/storage"
	"nexfi-backend/workers"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title NexFlux Virtual Lab API
// @version 1.0
// @description Backend API for NexFlux Virtual Lab - An interactive electronics learning platform
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email idnmakerspace@gmail.com
// @license.name MIT
// @license.url https://opensource.org/licenses/MIT
// @host localhost:8080
// @BasePath /api/v1
// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found")
	}

	// Initialize database
	database.InitDB()

	// Initialize Redis
	redis.InitRedis()

	// Initialize OAuth providers
	config.InitOAuthConfig()

	// Initialize cloud storage (MinIO or local)
	if err := storage.InitCloudStorage(); err != nil {
		log.Printf("Warning: Failed to initialize cloud storage: %v", err)
		// Fallback to old local storage
		if err := storage.InitStorage(); err != nil {
			log.Printf("Warning: Failed to initialize local storage: %v", err)
		}
	}

	// Run seeders (only seeds if data doesn't exist)
	if err := seeds.SeedDocumentation(database.DB); err != nil {
		log.Printf("Warning: Failed to seed documentation: %v", err)
	}
	if err := seeds.SeedLabs(database.DB); err != nil {
		log.Printf("Warning: Failed to seed labs: %v", err)
	}

	// Initialize MQTT client (VerneMQ) for lab hardware communication
	if err := mqtt.InitMQTT(); err != nil {
		log.Printf("Warning: Failed to initialize MQTT (VerneMQ): %v", err)
		log.Printf("Lab hardware communication will not be available")
	} else {
		log.Println("📡 MQTT (VerneMQ) initialized for lab hardware communication")
	}

	// Initialize RabbitMQ for job queues
	if err := rabbitmq.InitRabbitMQ(); err != nil {
		log.Printf("Warning: Failed to initialize RabbitMQ: %v", err)
		log.Printf("Job queue processing will not be available")
	} else {
		log.Println("🐰 RabbitMQ initialized for job queues")
	}

	// Initialize LiveKit for video streaming
	if err := livekit.InitLiveKit(); err != nil {
		log.Printf("Warning: Failed to initialize LiveKit: %v", err)
		log.Printf("Lab video streaming will not be available")
	} else {
		log.Println("🎬 LiveKit initialized for video streaming")
	}

	// Start lab workers (RabbitMQ job consumers)
	labWorker := workers.NewLabWorker(database.DB)
	labWorker.Start()

	// Set Gin mode based on environment
	if os.Getenv("GO_ENV") == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// Initialize Gin router
	router := gin.Default()

	// Swagger route
	router.GET("/swagger/*any", func(c *gin.Context) {
		host := c.Request.Host
		swaggerURL := ginSwagger.URL("http://" + host + "/swagger/doc.json")
		ginSwagger.WrapHandler(swaggerFiles.Handler, swaggerURL)(c)
	})

	// Setup routes
	routes.SetupRoutes(router, database.DB)

	// Get port from environment
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("🚀 NexFlux Virtual Lab API running on port %s", port)
	log.Printf("📚 Swagger docs available at http://localhost:%s/swagger/index.html", port)

	// Run the server
	if err := router.Run(":" + port); err != nil {
		log.Fatal("Failed to start server:", err)
	}
}
